### ISSUE TITLE
Skip type checking on production

### ISSUE THREAD

**Issue by likerRr** [hustcc/variable-type#2]
I believe it's nice to have type checking when working with weak dynamic types, especially with shapes. As far as I know type checking makes sense during developing process or for those people who will read the code in order to have understanding with what types of variables the code works. Languages with type checking will not compile your code until types are correct. So, in runtime it basically makes no sense to check types of variables.
Modern building tools during a building process can read variables from node's environment and replace their value with booleans, e.g.:

```javascript
// source
if (process.env.NODE_ENV === 'production') {

}

// build (in case if NODE_ENV = production)
if (true) {

}
``` 

After that minifiers (like uglifyjs) can exclude such code which is always under `false` block, because it's never used. This helps to avoid unnecessary calculations on production. React's [`prop-types`](https://github.com/facebook/prop-types/blob/master/index.js) does exactly like that. 

@hustcc What do you thing about adding the same behavior to `variable-type`?

**Comment by hustcc** [comment]
`variable-type` is for variable check, not for react prop types check. React's prop-types just for developer to dev React app.

If developer want to use `variable-type` for dev, he can do it by self.

I use it in this case:

1. users can upload a json file into our website.
2. our website should render the json into react jsx.

So, we should draw up a standard for the json file, then variable-type born.

**Comment by likerRr** [comment]
React's `prop-types` not only for component's props checks. Since it's a separate project it can be used for checking any variable's type in any project (I personally use it like this).

The idea I want to explain that in production build there is almost no use cases of real-time type checking. Developer should get and fix any issues with types in a code during development\testing process. After that the code is considered to be type checked. So you basically don't need extra code and calculations provided by the library in production, because types have already been checked.

**Comment by hustcc** [comment]
I know what is prop-types doing. But in my case, users will upload the json file in every time, I just use variable-type to check whether the json is valid.

Also it has been used in tcharts.js, for checking the function parameter which given by developers.

There are so many issues in prop-types, they want to use prop-types to check one var, and just for return true or false, not for warning text in console.
